# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param n the number of samples
#' @param a related to the distribution
#' @param b related to the distribution
#' @return a random matrix
#' @examples
#' \dontrun{
#' gibbsC1(1,2,10) 
#' } 
#' @importFrom stats rbinom rbeta
#' @export
gibbsC1 <- function(a, b, n) {
    .Call('_StatComp21002_gibbsC1', PACKAGE = 'StatComp21002', a, b, n)
}

